In [1]:
import numpy as np

In [2]:
array_0d = np.array(3)
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

In [4]:
print(array_0d)
print(array_1d)
print(array_2d)

3
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
array_1d.ndim

1

In [6]:
array_2d.size

9

In [9]:
array_2d.min()

1

In [10]:
array_2d.max()

9

In [11]:
array_2d.sum()

45

In [12]:
np.arange(5)  # like range(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(0,11,2)  # like range(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.linspace(0, 10, 5, dtype=float)  # return third_argument numbers, evenly spaced between first_argument and second_argument (both included)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [1, 2, 3, 4]])

In [17]:
arr_2d.shape

(4, 4)

In [19]:
arr_2d.mean()

5.5

In [20]:
np.median(arr_2d)

4.5

In [23]:
from scipy import stats

stats.mode(arr_2d)

ModeResult(mode=array([1, 2, 3, 4], dtype=int64), count=array([2, 2, 2, 2], dtype=int64))