In [1]:
import numpy as np

In [2]:
array_0d = np.array(3)
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

In [4]:
print(array_0d)
print(array_1d)
print(array_2d)

3
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
array_1d.ndim

1

In [6]:
array_2d.size

9

In [9]:
array_2d.min()

1

In [10]:
array_2d.max()

9

In [11]:
array_2d.sum()

45

In [12]:
np.arange(5)  # like range(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(0,11,2)  # like range(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.linspace(0, 10, 5, dtype=float)  # return third_argument numbers, evenly spaced between first_argument and second_argument (both included)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [1, 2, 3, 4]])

In [17]:
arr_2d.shape

(4, 4)

In [19]:
arr_2d.mean()

5.5

In [20]:
np.median(arr_2d)

4.5

In [23]:
from scipy import stats

stats.mode(arr_2d)

ModeResult(mode=array([1, 2, 3, 4], dtype=int64), count=array([2, 2, 2, 2], dtype=int64))

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [25]:
arr1 = np.array([[1, 2], 
                 [3, 4]])

arr2 = np.array([[5, 6], 
                 [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


<img src="https://numpy.org/doc/stable/_images/np_matrix_indexing.png" alt="600" width="700" align="left"/>

In [27]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [28]:
arr_2d[0,0]

1

In [29]:
arr_2d[0, :]

array([1, 2, 3, 4])

In [30]:
arr_2d[:,0]

array([1, 5, 9])

<img src="https://numpy.org/doc/stable/_images/np_ones_zeros_matrix.png" width="700" align="left"/>

In [35]:
np.zeros(2)  # zero-filled array, with floats by default

array([0., 0.])

In [32]:
np.zeros(2, dtype=int)

array([0, 0])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.ones(2)

array([1., 1.])

In [36]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [37]:
np.random.random(3)  # return an array with {argument} floats between 0 (included) and 1 (excluded)

array([0.35903816, 0.78651723, 0.85200741])

In [38]:
np.random.random((3,2))  # random-number 2d array with {first_argument} rows and {second_argument} columns

array([[0.69293921, 0.01156239],
       [0.84782285, 0.91709745],
       [0.52778886, 0.20970938]])

In [39]:
np.random.randint(0,100,(3,2))  # random integers from low (included) to high (excluded)

array([[22, 25],
       [58, 32],
       [ 9, 27]])

In [40]:
elements = np.random.randint(0,1000,(1,10))


x = np.std(elements)  # standard deviation
print(elements)
print(x)

[[334 159 632 424 364 129  70 990 931 990]]
342.6342218751653


In [41]:
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

x = np.percentile(ages, 75)  # e.g. 75th percentile

print(x)

43.0


<img src="https://www.w3resource.com/w3r_images/numpy-array-eye-function-image-1-b.png" width="200" align="left"/>

In [42]:
np.eye(2)  # e.g. 2d identity matrix

array([[1., 0.],
       [0., 1.]])

<img src="https://numpy.org/doc/stable/_images/np_reshape.png" width="600" align="left"/>

In [43]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [44]:
arr_2d_res = arr_2d.reshape(4,3)  # reshape the array into another with 4 rows and 3 columns
print(arr_2d_res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
arr_1d= np.array([1, 2, 3, 4, 5])

In [46]:
print(arr_1d < 3)

[ True  True False False False]


In [47]:
print(arr_1d[arr_1d < 3])  # boolean indexing

[1 2]


In [48]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [49]:
print(arr_2d < 3)

[[ True  True False False]
 [False False False False]
 [False False False False]]


In [50]:
print(arr_2d[arr_2d < 3])

[1 2]


In [52]:
np.where(arr_2d < 4, 1, 0)  # substitute (NOT the original) those values respecting the condition with second_argument, otherwise with third_argument

array([[1, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
A = np.random.rand(10000, 10000)  # random samples of the given shape from a uniform distribution over [0, 1)
a = A.tolist()  # transform a numpy array into a standard list

In [55]:
# time using a standard list
%%time
total = 0
for row in a:
    for n in row:
        total += n
round(total, 2)

CPU times: total: 156 ms
Wall time: 4.94 s


50003797.53

In [56]:
# time using a numpy array
%%time
round(np.sum(A), 2)

CPU times: total: 31.2 ms
Wall time: 64.6 ms


50003797.53

In [57]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [58]:
a+b

array([5, 7, 9])

In [59]:
a-b

array([-3, -3, -3])

In [61]:
a*3

array([3, 6, 9])

In [64]:
c= np.array([1,0]) 
d= np.array([0,1]) 

e= np.array([1,2,3])
f= np.array([2,4,6])

# dot product
print(np.dot(c,d))
print(np.dot(e,f))

0
28


In [65]:
M_1= np.array([[1,2,3],
               [0,1,2]]) 

M_2= np.array([[4,5],
               [6,7],
               [8,9]])

print(np.dot(M_1,M_2))  # matrix product

[[40 46]
 [22 25]]


In [66]:
M_1 @ M_2  # alternative for matrix product

array([[40, 46],
       [22, 25]])