# Exercise 1 #
- Use the np.arange() function to create an array of positive integers from 10 to 49 (included)
- Verify the type of the array and print the result
- Change the type to 'float64' and re-verify the type
- Print the shape of the array

In [37]:
import numpy as np

array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [38]:
print(array.dtype)

int32


In [39]:
array = array.astype('float64')
print(array)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [40]:
print(array.dtype)

float64


In [41]:
print(array.shape)

(40,)


# Exercise 2 #
- Create a 1D numpy array with 20 random integers between 10 and 50
- Slice to extract the first 10 elements
- Slice to extract the last 5 elements
- Slice to extract elements from index 5 to 15 (excluded)
- Slice to extract every third element
- Modify, by slicing, elements from index 5 to 10 (excluded), making them equal to 99
- Print the original array and all the outputs of the previous instructions

In [42]:
import numpy as np

og_array = np.random.choice(np.arange(10,51),20,replace=False)

In [43]:
first_10 = og_array[:10]

In [44]:
last_5 = og_array[-5:]

In [45]:
from_5_to_15 = og_array[5:15]

In [46]:
every_third = og_array[2::3]

In [47]:
modified_5_to_10 = og_array.copy()
modified_5_to_10[5:10] = [99 for _ in range(5,10)]

In [48]:
print(og_array)
print(first_10)
print(last_5)
print(from_5_to_15)
print(every_third)
print(modified_5_to_10)

[45 25 27 38 17 20 30 40 37 34 41 16 39 35 24 21 44 32 31 50]
[45 25 27 38 17 20 30 40 37 34]
[21 44 32 31 50]
[20 30 40 37 34 41 16 39 35 24]
[27 20 37 16 24 32]
[45 25 27 38 17 99 99 99 99 99 41 16 39 35 24 21 44 32 31 50]


# Exercise 3 #
- Create an array using linspace() with 12 numbers between 0 and 1
- Change its shape into a 3x4 matrix
- Create a 3x4 matrix with random numbers between 0 and 1
- Sum the two matrices and print the result

In [49]:
first_matrix = np.linspace(0,1,12)
print(first_matrix)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [50]:
first_matrix = first_matrix.reshape((3,4))
print(first_matrix)

[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]


In [51]:
second_matrix = np.random.rand(3,4)
print(second_matrix)

[[0.13294609 0.89740232 0.52914454 0.86328142]
 [0.61461931 0.40352094 0.64839746 0.76483364]
 [0.02097202 0.96840442 0.05986314 0.58082723]]


In [52]:
matrix_sum = first_matrix + second_matrix
print(matrix_sum)

[[0.13294609 0.98831141 0.71096272 1.13600869]
 [0.97825567 0.8580664  1.193852   1.40119727]
 [0.74824475 1.78658624 0.96895405 1.58082723]]


# Exercise 4 #
- Create an array using linspace() with 50 numbers between 0 and 10
- Use np.random.random to create an array of 50 random numbers between 0 and 1
- Sum the two arrays element by element to obtain a new array
- Calculate the total sum of this new array
- Calculate the sum of the elements > 5
- Print the original arrays, the sum array, and the other calculated sums

In [53]:
first_array = np.linspace(0,10,50)

In [54]:
second_array = np.random.random((50))

In [55]:
array_sum = first_array + second_array

In [56]:
total_sum = array_sum.sum()

In [57]:
sum_when_greater_than_5 = array_sum[array_sum > 5].sum()

In [58]:
print(first_array)
print(second_array)
print(array_sum)
print(total_sum)
print(sum_when_greater_than_5)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[0.0330681  0.23505385 0.49338225 0.05014931 0.90720476 0.66598661
 0.8139212  0.96219904 0.89088982 0.64942103 0.99122142 0.12357392
 0.40974878 0.26027814 0.80748396 0.97371262 0.64453625 0.72226551
 0.77980184 0.85324179 0.10309871 0.82290192 0.91914697 0.42479296
 0.18620609 0.1566137  0.9322905  0.32601804 0.19141588 0.0126961
 0.84354578 0.50503488 0.49723687 0.33234805 0.39763071 

# Exercise5 #
Write a program that uses numpy to manage a 2D matrix: the user has a menu where they can choose what to do with the matrix. Available operations:
- create a new 2D matrix with given shape and filled with random numbers
- extract and print the central sub-matrix
- transpose the matrix and print the result
- calculate and print the sum of all elements of the matrix
- exit the program

In [59]:
import numpy as np

In [60]:
def rng_matrix(shape, lower=0, upper=1):
    array = np.random.uniform(low=lower,high=upper,size=shape)
    return array

In [61]:
# for this to work, initial_dimension - final_dimension must be an even number, and matrix must be a 2D numpy array big enough
def central_sub_matrix(matrix, final_rows=None, final_columns=None):
    initial_rows = matrix.shape[0]
    initial_columns = matrix.shape[1]
    if final_rows is None:
        final_rows=initial_rows-2
    if final_columns is None:
        final_columns=initial_columns-2
    final = matrix.copy()
    half_rows_to_skip = int((initial_rows-final_rows)/2)
    half_columns_to_skip = int((initial_columns-final_columns)/2)
    final = final[half_rows_to_skip:initial_rows-half_rows_to_skip,half_columns_to_skip:initial_columns-half_columns_to_skip]
    return final

In [62]:
def transpose(matrix):
    transposed = np.zeros(matrix.shape[::-1])
    for column in np.arange(transposed.shape[1]):
        transposed[:,column] = matrix[column,:]
    return transposed

In [63]:
def sum_all(matrix):
    total = matrix.sum()
    return total

In [75]:
def matrix_management(matrix=None):
    while True:
        try:
            choice = input("Choose an option:\n    1) Create a 2D matrix\n    2) Extract a central sub-matrix\n    3) Transpose the matrix\n    4) Sum all elements\n    5) Exit\n")
            assert choice.isdigit() and int(choice) in (1,2,3,4,5)
            choice = int(choice)
        except:
            print("Wrong input")
            continue
        if matrix is None and choice in (2,3,4):
            print("You must create a matrix first, or select 5) to exit")
            continue
        if choice == 1:  # no more input checks from now on, takes too long
            shape = input("Type the new shape:\n")
            shape = eval(shape)
            change = int(input("Default bounds are 0 (included) and 1 (excluded). Would you like to change them?\n    1) No\n    2) Yes\n"))-1
            if change:
                lower_bound = float(input("Type the lower bound:\n"))
                upper_bound = float(input("Type the upper bound:\n"))
                new_matrix = rng_matrix(shape=shape,lower=lower_bound,upper=upper_bound)
                return new_matrix
            else:
                new_matrix = rng_matrix(shape=shape)
                return new_matrix
        elif choice == 2:
            print("Remember that (initial_dimension - final_dimension) must be an even number")
            print(f'Initial rows: {matrix.shape[0]}\nInitial columns: {matrix.shape[1]}')
            rows = int(input("How many final rows would you like the central sub-matrix to have?\n"))
            columns = int(input("How many final columns would you like the central sub-matrix to have?\n"))
            return central_sub_matrix(matrix=matrix,final_rows=rows,final_columns=columns)
        elif choice == 3:
            return transpose(matrix=matrix)
        elif choice == 4:
            return sum_all(matrix=matrix)
        else:
            break

In [77]:
mat = matrix_management()
print(mat)

[[0.04923356 0.05149655 0.7076816  0.25080564 0.59798388 0.7511663
  0.84973665 0.07460807 0.88332568 0.50857909 0.76109711]
 [0.89528609 0.70005693 0.48277346 0.48685212 0.41626691 0.04533403
  0.47848657 0.88736978 0.37966926 0.45746313 0.97355062]
 [0.16186687 0.88116277 0.40531079 0.34771503 0.47222015 0.35271709
  0.30989414 0.98759989 0.56881128 0.89770117 0.11870581]
 [0.40201197 0.91467842 0.68088585 0.92065541 0.99685292 0.08491281
  0.74307318 0.68064714 0.36500815 0.75997121 0.04191485]
 [0.07586542 0.62246364 0.85363239 0.80020651 0.24997387 0.85571964
  0.77690944 0.11571377 0.24896377 0.36245778 0.31144364]
 [0.403662   0.52077615 0.98707704 0.49826327 0.79722677 0.33172573
  0.33742091 0.10003685 0.42075903 0.00305428 0.62018844]
 [0.28043978 0.77402544 0.50452196 0.22679356 0.77235166 0.20442136
  0.86601219 0.1881554  0.85695465 0.97930738 0.29361545]
 [0.48567657 0.10162167 0.26982279 0.12003696 0.61513736 0.88613641
  0.23493646 0.84680839 0.05824209 0.45316571 0.024

In [78]:
mat = matrix_management()
print(mat)

[[0.01652936 0.4536561  0.28737723 0.83805994 0.7798679 ]
 [0.64528006 0.87541531 0.62264571 0.00151355 0.53939471]
 [0.02285469 0.94786145 0.64667236 0.03860745 0.43658447]
 [0.26471577 0.58342662 0.89545937 0.29739391 0.83804298]
 [0.32614118 0.34629759 0.50602718 0.14027289 0.57360294]]


In [79]:
sub_mat = matrix_management(mat)
print(sub_mat)

Remember that (initial_dimension - final_dimension) must be an even number
Initial rows: 5
Initial columns: 5
[[0.87541531 0.62264571 0.00151355]
 [0.94786145 0.64667236 0.03860745]
 [0.58342662 0.89545937 0.29739391]]


In [81]:
transpose_mat = matrix_management(mat)
print(transpose_mat)

[[0.01652936 0.64528006 0.02285469 0.26471577 0.32614118]
 [0.4536561  0.87541531 0.94786145 0.58342662 0.34629759]
 [0.28737723 0.62264571 0.64667236 0.89545937 0.50602718]
 [0.83805994 0.00151355 0.03860745 0.29739391 0.14027289]
 [0.7798679  0.53939471 0.43658447 0.83804298 0.57360294]]


In [82]:
sum_mat = matrix_management(mat)
print(sum_mat)

11.923700704645924
