# Exercise 1 #
- Use the np.arange() function to create an array of positive integers from 10 to 49 (included)
- Verify the type of the array and print the result
- Change the type to 'float64' and re-verify the type
- Print the shape of the array

In [190]:
import numpy as np

array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [191]:
print(array.dtype)

int32


In [192]:
array = array.astype('float64')
print(array)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [193]:
print(array.dtype)

float64


In [194]:
print(array.shape)

(40,)


# Exercise 2 #
- Create a 1D numpy array with 20 random integers between 10 and 50
- Slice to extract the first 10 elements
- Slice to extract the last 5 elements
- Slice to extract elements from index 5 to 15 (excluded)
- Slice to extract every third element
- Modify, by slicing, elements from index 5 to 10 (excluded), making them equal to 99
- Print the original array and all the outputs of the previous instructions

In [195]:
import numpy as np

og_array = np.random.choice(np.arange(10,51),20,replace=False)

In [196]:
first_10 = og_array[:10]

In [197]:
last_5 = og_array[-5:]

In [198]:
from_5_to_15 = og_array[5:15]

In [199]:
every_third = og_array[2::3]

In [200]:
modified_5_to_10 = og_array.copy()
modified_5_to_10[5:10] = [99 for _ in range(5,10)]

In [201]:
print(og_array)
print(first_10)
print(last_5)
print(from_5_to_15)
print(every_third)
print(modified_5_to_10)

[14 11 12 35 13 31 34 26 44 20 25 15 37 33 46 39 49 32 18 23]
[14 11 12 35 13 31 34 26 44 20]
[39 49 32 18 23]
[31 34 26 44 20 25 15 37 33 46]
[12 31 44 15 46 32]
[14 11 12 35 13 99 99 99 99 99 25 15 37 33 46 39 49 32 18 23]


# Exercise 3 #
- Create an array using linspace() with 12 numbers between 0 and 1
- Change its shape into a 3x4 matrix
- Create a 3x4 matrix with random numbers between 0 and 1
- Sum the two matrices and print the result

In [202]:
first_matrix = np.linspace(0,1,12)
print(first_matrix)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [203]:
first_matrix = first_matrix.reshape((3,4))
print(first_matrix)

[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]


In [204]:
second_matrix = np.random.rand(3,4)
print(second_matrix)

[[0.61217437 0.33283034 0.39964296 0.52245587]
 [0.85332456 0.17668254 0.92722054 0.6713428 ]
 [0.2446618  0.66172762 0.28084123 0.11555388]]


In [205]:
matrix_sum = first_matrix + second_matrix
print(matrix_sum)

[[0.61217437 0.42373943 0.58146114 0.79518314]
 [1.21696092 0.63122799 1.47267509 1.30770643]
 [0.97193453 1.47990944 1.18993214 1.11555388]]


# Exercise 4 #
- Create an array using linspace() with 50 numbers between 0 and 10
- Use np.random.random to create an array of 50 random numbers between 0 and 1
- Sum the two arrays element by element to obtain a new array
- Calculate the total sum of this new array
- Calculate the sum of the elements > 5
- Print the original arrays, the sum array, and the other calculated sums

In [206]:
first_array = np.linspace(0,10,50)

In [207]:
second_array = np.random.random((50))

In [208]:
array_sum = first_array + second_array

In [209]:
total_sum = array_sum.sum()

In [210]:
sum_when_greater_than_5 = array_sum[array_sum > 5].sum()

In [211]:
print(first_array)
print(second_array)
print(array_sum)
print(total_sum)
print(sum_when_greater_than_5)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[0.10219957 0.52879849 0.96185296 0.74642934 0.70575333 0.65149465
 0.67732532 0.16803008 0.93708788 0.2399624  0.85137164 0.52689623
 0.03981122 0.95296576 0.05489043 0.35070534 0.04583813 0.20393429
 0.97289731 0.80481076 0.42766782 0.66265138 0.23437963 0.65230977
 0.26082997 0.17052227 0.02963472 0.44575988 0.56379646 0.39960375
 0.00916386 0.66694185 0.72914439 0.07290157 0.102906  