# Exercise 1 #
- Use the np.arange() function to create an array of positive integers from 10 to 49 (included)
- Verify the type of the array and print the result
- Change the type to 'float64' and re-verify the type
- Print the shape of the array

In [121]:
import numpy as np

array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [122]:
print(array.dtype)

int32


In [123]:
array = array.astype('float64')
print(array)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [124]:
print(array.dtype)

float64


In [125]:
print(array.shape)

(40,)


# Exercise 2 #
- Create a 1D numpy array with 20 random integers between 10 and 50
- Slice to extract the first 10 elements
- Slice to extract the last 5 elements
- Slice to extract elements from index 5 to 15 (excluded)
- Slice to extract every third element
- Modify, by slicing, elements from index 5 to 10 (excluded), making them equal to 99
- Print the original array and all the outputs of the previous instructions

In [126]:
import numpy as np

og_array = np.random.choice(np.arange(10,51),20,replace=False)

In [127]:
first_10 = og_array[:10]

In [128]:
last_5 = og_array[-5:]

In [129]:
from_5_to_15 = og_array[5:15]

In [130]:
every_third = og_array[2::3]

In [131]:
modified_5_to_10 = og_array[:].copy()
modified_5_to_10[5:10] = [99 for _ in range(5,10)]

In [132]:
print(og_array)
print(first_10)
print(last_5)
print(from_5_to_15)
print(every_third)
print(modified_5_to_10)

[49 34 27 14 17 47 45 38 29 15 19 39 40 26 11 28 46 33 31 32]
[49 34 27 14 17 47 45 38 29 15]
[28 46 33 31 32]
[47 45 38 29 15 19 39 40 26 11]
[27 47 29 39 11 33]
[49 34 27 14 17 99 99 99 99 99 19 39 40 26 11 28 46 33 31 32]
